### ISSUE TITLE
ENH: OCV from EIS data

### ISSUE THREAD

**Issue by fg-personal** [SF-Tec/pyvium#47]
### Feature Type

- [X] Adding new functionality to pyvium

- [X] Changing existing functionality in pyvium

- [ ] Removing existing functionality in pyvium

### Problem Description

I wish I could use pyvium to grab both EIS data at different frequencies and the values of open circuit voltage measured before the experiment. Is it possible at all?

### Feature Description

While setting up an EIS measurement you can select "Apply wrt OCP", a monitor time and  a monitor interval. However, that information is lost if I just use Tools.get_idf_data and it can be crucial to have.

### Alternative Solutions

(...)

**Comment by Gnpd** [comment]
Thank you for bringing this up! I understand that the `get_idf_data` function currently does not handle OCP data and only extracts the primary data from the IDF file.

To address this, I plan to modify the `get_idf_data` function to optionally retrieve OCP data. For example, it could include an optional parameter like `get_idf_data(idf_path, ocp=True)` (or equivalent). This enhancement should provide the additional functionality you’re looking for while maintaining the current behavior as the default.

I’m already working on this and expect to have it implemented within the next week. I’ll update this thread as soon as the changes are ready for you to test.

Thanks again for your feedback—it helps us improve the library for all users!

**Comment by Gnpd** [comment]
Hello @fg-personal , thanks for your patient! ;-)

There is a new `get_all_idf_data` function in the `DataProcessing` class designed to extract all data (both primary and extra measurement data) from an IDF file and return it as a dictionary. For EIS data it will return various data sections if available (primary data, OCP data, pretreatment data, RsCs data, and OSC data). 

#### Function Signature
```python
@staticmethod
def get_all_idf_data(idf_path: str) -> Dict[str, List[List[int]]]:
```
- **Arguments**:
  - `idf_path` (str): The path to the IDF file.
- **Returns**:
  - A dictionary where the keys are data section names (e.g., "primary_data", "ocpdata", etc.) and the values are lists of lists of integers representing the extracted data.

Please give it a try and let us know if it works for you or if you encounter any issues. We’re happy to help!

**Comment by fg-personal** [comment]
error for code
```
myfilename = "test.idf"
#Tools.convert_idf_to_csv(myfilename)
EISdata = Tools.get_all_idf_data(myfilename)
```
the test file has OCV data within

error info
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2024.3.3\plugins\python-ce\helpers\pydev\pydevd.py", line 1570, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2024.3.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\username\pyproj\ivium\ConvertIvium.py", line 25, in <module>
    EISdata = Tools.get_all_idf_data(myfilename)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\pyproj\ivium\my_venv\Lib\site-packages\pyvium\tools\data_processing_functions.py", line 81, in get_all_idf_data
    data["osc_data"] = extract_osc_data(lines, index)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\pyproj\ivium\my_venv\Lib\site-packages\pyvium\tools\data_processing_functions.py", line 63, in extract_osc_data
    num_sections = int(lines[start_index + 1])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '\x0031        '
python-BaseException
```

extra info on the measurement file being processed
> 0013 = {str} 'software=41170'
0014 = {str} 'firmware=1092'
0100 = {str} 'Apply wrt OCP=true'
0101 = {str} 'Apply wrt OCP.Monitor time=60'
0102 = {str} 'Apply wrt OCP.Monitor interval=1'
0103 = {str} 'Apply wrt OCP.Estart wrt OCP=true'
0104 = {str} 'Apply wrt OCP.Vtx/End wrt OCP=false'
0105 = {str} 'Apply wrt OCP.Estandby wrt OCP=true'
0106 = {str} 'Apply wrt OCP.Record real E=false'
0107 = {str} 'Apply wrt OCP.Accept if dE/dt<=0.01'

**Comment by Gnpd** [comment]
Hello @fg-personal can you attach your idf file?
or sent it to info@sftec.es?

Thanks!

**Comment by fg-personal** [comment]
Sure

[test.zip](https://github.com/user-attachments/files/19087382/test.zip)

**Comment by Gnpd** [comment]
hello @fg-personal , It should work safely now.
